# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b02982765e580215e0cf78e149dc62d43b31a4730a0ba0bb677da64fb0eef73af9c7b8609a0ad9a7bb3027ad2950a4c827d2731471b2f2cd5da4e9c4f3bba3c0

test:
  secret_key_base: 5465fc9fe51e3797dd1f766da008e597d6037bbc2c2ba2bc041d51cf9ad54fe33cf7115f63cc3b8e786fe4fe19130029203f6c6c90fc8dbfbaa6904202d3fade

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
